quarkus.application.name=quarkus-mongo-demo
quarkus.http.port=8081

quarkus.mongodb.primary.connection-string=mongodb://localhost:27017
quarkus.mongodb.primary.database=db_primary

quarkus.mongodb.secondary.connection-string=mongodb://localhost:27017
quarkus.mongodb.secondary.database=db_secondary
